# Generated by Django 2.2.2 on 2020-05-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '掲示板', 'verbose_name_plural': '掲示板'},
        ),
        migrations.AlterField(
            model_name='board',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='readtext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
