# Generated by Django 2.2.2 on 2020-05-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200504_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
