# Generated by Django 2.2.2 on 2020-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20200504_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='goodtext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
